spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Users
    username: root
    password: Muhaz8164@
    driver-class-name: com.mysql.cj.jdbc.Driver
